# Generated by Django 5.0.1 on 2024-02-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarLicenseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('needs_check', models.BooleanField(default=False)),
                ('renewal_duration', models.IntegerField(choices=[(1, '1 Year'), (2, '2 Years'), (3, '3 Years')])),
                ('visit_date', models.DateTimeField()),
                ('visit_slot', models.CharField(blank=True, max_length=32, null=True)),
                ('vip_assistance', models.BooleanField(default=False)),
                ('is_new_car', models.BooleanField(default=False)),
                ('contract', models.ImageField(blank=True, null=True, upload_to='contracts/')),
                ('license_id_image', models.ImageField(blank=True, null=True, upload_to='license_ids/')),
                ('national_id_image', models.ImageField(upload_to='national_ids/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
