# Generated by Django 5.0.1 on 2024-02-03 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_license_orders', '0001_initial'),
        ('driver_license_orders', '0001_initial'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlicenseorder',
            name='licensing_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='driver_license_orders.licensingunit'),
        ),
        migrations.AddField(
            model_name='carlicenseorder',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car_license_rating', to='ratings.rating'),
        ),
    ]
