# Generated by Django 5.0.1 on 2024-02-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_license_orders', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlicenseorder',
            name='installment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carlicenseorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='carlicenseorder',
            name='status',
            field=models.CharField(choices=[('WAITINGAPPROVAL', 'Waitingapproval'), ('PENDING', 'Pending'), ('DONE', 'Done'), ('REJECTED', 'Rejected')], default='WAITINGAPPROVAL', max_length=32, null=True),
        ),
    ]
