# Generated by Django 5.0.1 on 2024-02-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_license_orders', '0004_carlicenseorder_installment_carlicenseorder_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlicenseorder',
            name='status',
            field=models.CharField(choices=[('WAITING_APPROVAL', 'Waiting Approval'), ('PENDING', 'Pending'), ('DONE', 'Done'), ('REJECTED', 'Rejected')], default='WAITING_APPROVAL', max_length=32, null=True),
        ),
    ]
