# Generated by Django 5.0.1 on 2024-02-03 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicensingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriverLicenseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('needs_check', models.BooleanField(default=False)),
                ('renewal_duration', models.IntegerField(choices=[(1, '1 Year'), (2, '2 Years'), (3, '3 Years')])),
                ('visit_date', models.DateTimeField()),
                ('visit_slot', models.CharField(blank=True, max_length=32, null=True)),
                ('vip_assistance', models.BooleanField(default=False)),
                ('is_new_car', models.BooleanField(default=False)),
                ('contract_image', models.ImageField(blank=True, null=True, upload_to='contracts/')),
                ('license_id_image', models.ImageField(blank=True, null=True, upload_to='license_ids/')),
                ('national_id_image', models.ImageField(upload_to='national_ids/')),
                ('rating', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_license_rating', to='ratings.rating')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
