# Generated by Django 5.0.1 on 2024-02-03 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver_license_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlicenseorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_license_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverlicenseorder',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='driver_license_orders.governorate'),
        ),
        migrations.AddField(
            model_name='licensingunit',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governorate', to='driver_license_orders.governorate'),
        ),
        migrations.AddField(
            model_name='driverlicenseorder',
            name='licensing_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='driver_license_orders.licensingunit'),
        ),
    ]
