# Generated by Django 5.0.1 on 2024-02-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_license_orders', '0004_alter_driverlicenseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlicenseorder',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
