# Generated by Django 5.0.1 on 2024-02-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_license_orders', '0005_driverlicenseorder_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlicenseorder',
            name='renewal_duration',
        ),
    ]
